version: '3.9'
services:
  customer:
    build:
      context: ./customer
      dockerfile: ./docker/Dockerfile
      args:
        - BUILD_COMMAND=docker build ./customer -f ./customer/docker/Dockerfile -t customer --no-cache
    image: customer:latest
    ports:
      - 8000:8000
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - my-network
  account:
    build:
      context: ./account
      dockerfile: ./docker/Dockerfile
      args:
        - BUILD_COMMAND=docker build ./account -f ./account/docker/Dockerfile -t account --no-cache
    image: account:latest
    ports:
      - 8001:8001
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - my-network
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - my-network
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
